In [3]:
import pandas as pd

df=pd.read_csv('Data/AviationData.csv', encoding='latin-1')
df

C:\Users\johns\anaconda3\envs\learn-env\lib\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (6,7,28) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.9222,-81.8781,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88884,20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,29-12-2022
88885,20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
88887,20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,...,Personal,MC CESSNA 210N LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88888,20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,30-12-2022

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      88889 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50249 non-null  object
 9   Airport.Name            52790 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87572 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81812 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82508 non-null  object
 30  Publication.Date        75118 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.0+ MB

In [11]:
df.isnull().sum()
df['Location'].value_counts()

ANCHORAGE, AK             434
MIAMI, FL                 200
ALBUQUERQUE, NM           196
HOUSTON, TX               193
CHICAGO, IL               184
                         ...
DAVENPORT, NE               1
Onalaska, TX                1
Birr, Ireland, Ireland      1
Lincolnton, GA              1
BERGAMO, ITALY              1
Name: Location, Length: 27758, dtype: int64

In [12]:
column_names = list(df.columns)


for x in column_names:
    print(df[x].value_counts())

20001214X45071    3
20001212X19172    3
20001211X14328    2
20001208X09058    2
20051206X01938    2
                 ..
20200423X91852    1
20081003X17530    1
20001213X29117    1
20151005X12529    1
20001213X25826    1
Name: Event.Id, Length: 87951, dtype: int64
Accident    85015
Incident     3874
Name: Investigation.Type, dtype: int64
ERA22FA318    2
ERA22LA119    2
CEN22LA149    2
DCA23WA071    2
ERA22LA364    2
             ..
ERA10LA349    1
CHI85LA203    1
CEN21LA363    1
CEN11CA624    1
ANC14FA062    1
Name: Accident.Number, Length: 88863, dtype: int64
1982-05-16    25
1984-06-30    25
2000-07-08    25
1986-05-17    24
1983-06-05    24
              ..
2012-12-16     1
2019-02-19     1
2016-02-19     1
2014-08-04     1
2017-01-13     1
Name: Event.Date, Length: 14782, dtype: int64
ANCHORAGE, AK             434
MIAMI, FL                 200
ALBUQUERQUE, NM           196
HOUSTON, TX               193
CHICAGO, IL               184
                         ...
DAVENPORT, NE               1
Onalaska, TX                1
Birr, Ireland, Ireland      1
Lincolnton, GA              1
BERGAMO, ITALY              1
Name: Location, Length: 27758, dtype: int64
United States                    82248
Brazil                             374
Canada                             359
Mexico                             358
United Kingdom                     344
                                 ...
Obyan                                1
St Vincent And The Grenadines        1
BLOCK 651A                           1
Sierra Leone                         1
French Guiana                        1
Name: Country, Length: 219, dtype: int64
332739N      19
335219N      18
32.815556    17
334118N      17
039405N      16
             ..
39.313056     1
301621N       1
043353N       1
431122N       1
37.910278     1
Name: Latitude, Length: 25592, dtype: int64
0112457W       24
1114342W       18
1151140W       17
-104.673056    17
1114840W       16
               ..
0002500E        1
0843544W        1
0791555W        1
0823426W        1
1125341W        1
Name: Longitude, Length: 27156, dtype: int64
NONE    1488
PVT      485
APA      160
ORD      149
MRI      137
        ...
5SC5       1
68FD       1
11Y        1
ATT        1
0CO5       1
Name: Airport.Code, Length: 10375, dtype: int64
Private               240
PRIVATE               224
Private Airstrip      153
NONE                  146
PRIVATE STRIP         111
                     ...
North View Airport      1
Cascade Airport         1
MCGAHAN INDUSTRIAL      1
JAARS-Townsend          1
ACKINAC ISLAND          1
Name: Airport.Name, Length: 24871, dtype: int64
Non-Fatal     67357
Fatal(1)       6167
Fatal          5262
Fatal(2)       3711
Incident       2219
              ...
Fatal(28)         1
Fatal(153)        1
Fatal(47)         1
Fatal(21)         1
Fatal(80)         1
Name: Injury.Severity, Length: 109, dtype: int64
Substantial    64148
Destroyed      18623
Minor           2805
Unknown          119
Name: Aircraft.damage, dtype: int64
Airplane             27617
Helicopter            3440
Glider                 508
Balloon                231
Gyrocraft              173
Weight-Shift           161
Powered Parachute       91
Ultralight              30
Unknown                 14
WSFT                     9
Powered-Lift             5
Blimp                    4
UNK                      2
Rocket                   1
ULTR                     1
Name: Aircraft.Category, dtype: int64
NONE      344
UNREG     126
None       65
UNK        13
USAF        9
         ...
N67853      1
N58969      1
N97EZ       1
N6917       1
N785SP      1
Name: Registration.Number, Length: 79105, dtype: int64
Cessna                       22227
Piper                        12029
CESSNA                        4922
Beech                         4330
PIPER                         2841
                             ...
Koen Lancair                     1
Blair-american                   1
Sigers                           1
BOYLE JOSEPH E                   1
NASA AMES RESEARCH CENTER        1
Name: Make, Length: 8237, dtype: int64
152                   2367
172                   1756
172N                  1164
PA-28-140              932
150                    829
                      ...
50M                      1
Volmer Amphibian B       1
BH206B-3                 1
VENTUS A/16.6            1
F-28-F                   1
Name: Model, Length: 12318, dtype: int64
No     80312
Yes     8475
Name: Amateur.Built, dtype: int64
1.0    69582
2.0    11079
0.0     1226
3.0      483
4.0      431
8.0        3
6.0        1
Name: Number.of.Engines, dtype: int64
Reciprocating      69530
Turbo Shaft         3609
Turbo Prop          3391
Turbo Fan           2481
Unknown             2051
Turbo Jet            703
None                  19
Geared Turbofan       12
Electric              10
LR                     2
NONE                   2
Hybrid Rocket          1
UNK                    1
Name: Engine.Type, dtype: int64
091                               18221
Part 91: General Aviation          6486
NUSN                               1584
NUSC                               1013
137                                1010
135                                 746
121                                 679
Part 137: Agricultural              437
UNK                                 371
Part 135: Air Taxi & Commuter       298
PUBU                                253
129                                 246
Part 121: Air Carrier               165
133                                 107
Part 129: Foreign                   100
Non-U.S., Non-Commercial             97
Non-U.S., Commercial                 93
Part 133: Rotorcraft Ext. Load       32
Unknown                              22
Public Use                           19
091K                                 14
ARMF                                  8
Part 125: 20+ Pax,6000+ lbs           5
125                                   5
107                                   4
Public Aircraft                       2
103                                   2
Part 91F: Special Flt Ops.            1
Part 91 Subpart K: Fractional         1
437                                   1
Armed Forces                          1
Name: FAR.Description, dtype: int64
NSCH    4474
UNK     4099
SCHD    4009
Name: Schedule, dtype: int64
Personal                     49448
Instructional                10601
Unknown                       6802
Aerial Application            4712
Business                      4018
Positioning                   1646
Other Work Use                1264
Ferry                          812
Aerial Observation             794
Public Aircraft                720
Executive/corporate            553
Flight Test                    405
Skydiving                      182
External Load                  123
Public Aircraft - Federal      105
Banner Tow                     101
Air Race show                   99
Public Aircraft - Local         74
Public Aircraft - State         64
Air Race/show                   59
Glider Tow                      53
Firefighting                    40
Air Drop                        11
ASHO                             6
PUBS                             4
PUBL                             1
Name: Purpose.of.flight, dtype: int64
Pilot                                    258
American Airlines                         90
United Airlines                           89
Delta Air Lines                           53
SOUTHWEST AIRLINES CO                     42
                                        ...
Over The Top Aviation Inc.                 1
Morris Ag Air & Sons, Inc.                 1
Janet L Liberty                            1
Roberto Reynal                             1
(dba: Arctic Circle Air Service, Inc)      1
Name: Air.carrier, Length: 13590, dtype: int64
0.0      59675
1.0       8883
2.0       5173
3.0       1589
4.0       1103
         ...
31.0         1
169.0        1
150.0        1
117.0        1
156.0        1
Name: Total.Fatal.Injuries, Length: 125, dtype: int64
0.0      63289
1.0       9125
2.0       2815
3.0        629
4.0        258
5.0         78
6.0         41
7.0         27
9.0         16
8.0         13
10.0        13
13.0         9
11.0         6
26.0         5
14.0         5
12.0         5
25.0         3
20.0         3
28.0         3
17.0         2
50.0         2
59.0         2
21.0         2
47.0         2
55.0         1
88.0         1
41.0         1
67.0         1
33.0         1
18.0         1
161.0        1
81.0         1
39.0         1
137.0        1
27.0         1
15.0         1
45.0         1
125.0        1
23.0         1
44.0         1
106.0        1
22.0         1
34.0         1
16.0         1
35.0         1
53.0         1
43.0         1
63.0         1
19.0         1
60.0         1
Name: Total.Serious.Injuries, dtype: int64
0.0      61454
1.0      10320
2.0       3576
3.0        784
4.0        372
5.0        129
6.0         67
7.0         59
9.0         22
8.0         20
13.0        14
12.0        11
10.0        11
14.0        10
11.0         9
17.0         8
18.0         6
19.0         6
22.0         5
24.0         5
15.0         4
33.0         4
16.0         4
25.0         4
23.0         3
21.0         3
32.0         3
20.0         3
27.0         3
26.0         3
30.0         2
36.0         2
42.0         2
28.0         2
38.0         2
50.0         2
31.0         2
43.0         1
39.0         1
65.0         1
47.0         1
57.0         1
58.0         1
29.0         1
45.0         1
62.0         1
71.0         1
200.0        1
125.0        1
96.0         1
69.0         1
380.0        1
68.0         1
171.0        1
35.0         1
40.0         1
84.0         1
Name: Total.Minor.Injuries, dtype: int64
0.0      29879
1.0      25101
2.0      15988
3.0       4313
4.0       2662
         ...
325.0        1
230.0        1
260.0        1
251.0        1
414.0        1
Name: Total.Uninjured, Length: 379, dtype: int64
VMC    77303
IMC     5976
UNK      856
Unk      262
Name: Weather.Condition, dtype: int64
Landing        15428
Takeoff        12493
Cruise         10269
Maneuvering     8144
Approach        6546
Climb           2034
Taxi            1958
Descent         1887
Go-around       1353
Standing         945
Unknown          548
Other            119
Name: Broad.phase.of.flight, dtype: int64

Probable Cause                                                                                                                                                                                                                       61754
Foreign                                                                                                                                                                                                                               1999
<br /><br />                                                                                                                                                                                                                           167
Factual                                                                                                                                                                                                                                145
The pilot's failure to maintain directional control during the landing roll.                                                                                                                                                            56
                                                                                                                                                                                                                                     ...
The noncertificated pilots improper decision to depart with a tailwind. \r\n\r                                                                                                                                                        1
The pilot's loss of directional control while taking off with a gusting wind.                                                                                                                                                            1
A loss of control due to spatial disorientation while climbing after departure in instrument meteorological conditions. Contributing to the accident was the pilot's lack of recent instrument experience.                               1
The failure of the right main landing gear strut due to corrosion-induced fatigue, which resulted in a runway excursion.                                                                                                                 1
The flight instructor did not maintain aircraft control while maneuvering at low altitude. Contributing to the accident was the inadvertent application of the choke, which resulted in a momentary interruption of engine power.        1
Name: Report.Status, Length: 17075, dtype: int64
25-09-2020    17019
26-09-2020     1769
03-11-2020     1155
31-03-1993      452
25-11-2003      396
              ...
08-04-2021        1
19-07-2005        1
05-12-2008        1
25-03-2003        1
07-02-2013        1
Name: Publication.Date, Length: 2924, dtype: int64

In [13]:
df.loc[df['Event.Id'] == '20001214X45071']

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
6781,20001214X45071,Accident,FTW84LA056C,1983-11-11,"HOUSTON, TX",United States,NaN,NaN,AAP,ANDRAU,...,Business,NaN,0.0,0.0,0.0,5.0,VMC,Standing,Probable Cause,19-03-2002
6784,20001214X45071,Accident,FTW84LA056B,1983-11-11,"HOUSTON, TX",United States,NaN,NaN,AAP,ANDRAU,...,Personal,NaN,0.0,0.0,0.0,5.0,VMC,Standing,Probable Cause,19-03-2002
6785,20001214X45071,Accident,FTW84LA056A,1983-11-11,"HOUSTON, TX",United States,NaN,NaN,AAP,ANDRAU,...,Personal,NaN,0.0,0.0,0.0,5.0,VMC,Taxi,Probable Cause,19-03-2002

In [18]:
subset = df.loc[(df['Injury.Severity'] == 'Fatal(1)') | (df['Injury.Severity'] == 'Fatal') | (df['Injury.Severity'] == 'Fatal(2)')]
# subset.sort_values(by = 'Total.Fatal.Injuries', ascending =False)
subset.sort_values(by = 'Event.Date', ascending =True)

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980
13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,NaN,NaN,T72,HEARNE MUNICIPAL,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,02-01-1983
14,20020917X02119,Accident,FTW82FPJ10,1982-01-02,"CHICKASHA, OK",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88843,20221205106408,Accident,CEN23FA057,2022-12-04,"Cleburne, TX",United States,321926N,0972553W,CPT,CLEBURNE RGNL,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,NaN,NaN,15-12-2022
88845,20221205106417,Accident,CEN23FA059,2022-12-05,"Corning, IA",United States,405957N,0944518W,CRZ,Corning Municipal Airport,...,Personal,PORTER STEVEN B,1.0,0.0,0.0,0.0,VMC,NaN,NaN,13-12-2022
88846,20221206106419,Accident,CEN23FA060,2022-12-05,"Yukon, OK",United States,352933N,0974927W,RCE,CLARENCE E PAGE MUNI,...,Personal,NaN,3.0,0.0,0.0,0.0,VMC,NaN,NaN,13-12-2022
88868,20221213106451,Accident,ERA23FA087,2022-12-13,"Kellyton, AL",United States,NaN,NaN,NaN,NaN,...,Executive/corporate,RAINWATER FARMS LLC,1.0,0.0,0.0,0.0,NaN,NaN,NaN,15-12-2022
88883,20221228106502,Accident,GAA23WA046,2022-12-22,"Brasnorte,",Brazil,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,0.0,0.0,0.0,NaN,NaN,NaN,28-12-2022

In [15]:
subset.isnull().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     14
Country                      39
Latitude                   8544
Longitude                  8544
Airport.Code               9030
Airport.Name               8790
Injury.Severity               0
Aircraft.damage             213
Aircraft.Category          9252
Registration.Number         304
Make                         15
Model                        21
Amateur.Built                17
Number.of.Engines          1654
Engine.Type                2033
FAR.Description            9395
Schedule                  13676
Purpose.of.flight          1343
Air.carrier               12287
Total.Fatal.Injuries          0
Total.Serious.Injuries     2035
Total.Minor.Injuries       2262
Total.Uninjured            2284
Weather.Condition          1427
Broad.phase.of.flight      5732
Report.Status              2244
Publication.Date           2011
dtype: int64